-- INSERT INTO preferences (user_id, male, female, pet_friendly)
-- VALUES (1, TRUE, TRUE, FALSE), (2, TRUE, FALSE, TRUE), (3, FALSE, TRUE, FALSE)

INSERT INTO preferences (user_id, male, female, other, pet_friendly)
VALUES (1, TRUE, TRUE, TRUE, TRUE), (2, TRUE, TRUE, TRUE, FALSE), (3, FALSE, TRUE, TRUE, TRUE), (4, TRUE, FALSE, TRUE, TRUE), 
(5, TRUE, FALSE, TRUE, TRUE), (6, TRUE, FALSE, TRUE, FALSE), (7, FALSE, TRUE, TRUE, TRUE), (8, FALSE, TRUE, TRUE, FALSE), 
(9, TRUE, FALSE, TRUE, FALSE), (10, FALSE, TRUE, TRUE, TRUE), (11, TRUE, TRUE, TRUE, TRUE), (12, TRUE, TRUE, TRUE, TRUE), (13, TRUE, TRUE, TRUE, FALSE)
